# Generated by Django 5.0 on 2023-12-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_list',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Low'), (2, 'Medium'), (1, 'High')], default=2),
        ),
    ]
